<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<RootNamespace>OurStory.Web</RootNamespace>
		<Description>ASP.NET Core 站点</Description>
		<UserSecretsId>ourstory-web</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="appsettings*.json" />
		<None Include="appsettings*.json" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OurStory.Services\OurStory.Services.csproj" />
	</ItemGroup>

</Project>
